### ISSUE TITLE
newUser API에 프로필도 등록받도록 하는건 어떤가요?

### ISSUE THREAD

**Issue by okps123** [Cheongmin/VoiceReader-Rest#2]
newUser API는 현재 `display_name`만 폼 데이터를 통해 받고 있지만 `photo_url`도 받도록 수정하는건 어떨까요?
애플리케이션단에서는 Firebase를 통해 주소만 받아올 수 있어서 아래와 같이 작업해야합니다.
1. 로컬 스토리지에 프로필 사진 다운로드
2. API서버에 멀티 파트 폼으로 업로드

서버에서 프로필 사진 주소를 받아 서버 내부 스토리지에 다운받는다면 간편하게 처리할 수 있을 것 같아요.

**Comment by gyuhwankim** [comment]
This suggestion accepted on #12
